# Generated by Django 6.0.5 on 2026-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
